// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module csi_udp_parser_csi_udp_parser_Pipeline_parse (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        rx_TVALID,
        csi_out_TREADY,
        rx_TDATA,
        rx_TREADY,
        rx_TKEEP,
        rx_TSTRB,
        rx_TLAST,
        udp_port,
        csi_out_TDATA,
        csi_out_TVALID,
        csi_out_TKEEP,
        csi_out_TSTRB,
        csi_out_TLAST,
        n_sub_3_out,
        n_sub_3_out_ap_vld,
        meta_core_spatial_1_out,
        meta_core_spatial_1_out_ap_vld,
        meta_chanspec_3_out,
        meta_chanspec_3_out_ap_vld,
        meta_rssi_2_out,
        meta_rssi_2_out_ap_vld,
        meta_seq_3_out,
        meta_seq_3_out_ap_vld,
        keep_1_out,
        keep_1_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   rx_TVALID;
input   csi_out_TREADY;
input  [7:0] rx_TDATA;
output   rx_TREADY;
input  [0:0] rx_TKEEP;
input  [0:0] rx_TSTRB;
input  [0:0] rx_TLAST;
input  [15:0] udp_port;
output  [31:0] csi_out_TDATA;
output   csi_out_TVALID;
output  [3:0] csi_out_TKEEP;
output  [3:0] csi_out_TSTRB;
output  [0:0] csi_out_TLAST;
output  [15:0] n_sub_3_out;
output   n_sub_3_out_ap_vld;
output  [7:0] meta_core_spatial_1_out;
output   meta_core_spatial_1_out_ap_vld;
output  [15:0] meta_chanspec_3_out;
output   meta_chanspec_3_out_ap_vld;
output  [7:0] meta_rssi_2_out;
output   meta_rssi_2_out_ap_vld;
output  [15:0] meta_seq_3_out;
output   meta_seq_3_out_ap_vld;
output  [0:0] keep_1_out;
output   keep_1_out_ap_vld;

reg ap_idle;
reg rx_TREADY;
reg csi_out_TVALID;
reg n_sub_3_out_ap_vld;
reg meta_core_spatial_1_out_ap_vld;
reg meta_chanspec_3_out_ap_vld;
reg meta_rssi_2_out_ap_vld;
reg meta_seq_3_out_ap_vld;
reg keep_1_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg    ap_block_state2_pp0_stage0_iter1;
reg   [0:0] icmp_ln35_reg_862;
reg   [15:0] idx_1_reg_848;
reg   [0:0] and_ln51_1_reg_866;
reg   [1:0] phase_load_reg_870;
reg    ap_predicate_op128_write_state3;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] beat_last_fu_358_p1;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    rx_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    csi_out_TDATA_blk_n;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_11001;
wire   [15:0] idx_1_load_fu_342_p1;
reg   [7:0] beat_data_reg_852;
reg   [0:0] beat_last_reg_857;
wire   [0:0] icmp_ln35_fu_362_p2;
wire   [0:0] and_ln51_1_fu_580_p2;
wire   [1:0] phase_load_load_fu_586_p1;
reg   [15:0] idx_fu_126;
wire   [15:0] idx_2_fu_348_p2;
wire    ap_loop_init;
reg   [7:0] b2_fu_130;
reg   [7:0] b1_fu_134;
reg   [7:0] b0_fu_138;
reg   [7:0] ip_proto_fu_142;
reg   [7:0] meta_rssi_fu_146;
reg    ap_loop_exit_ready_pp0_iter2_reg;
wire    ap_block_pp0_stage0_grp0;
reg   [7:0] meta_core_spatial_fu_150;
reg   [15:0] n_sub_fu_154;
wire   [15:0] n_sub_3_fu_644_p2;
reg   [15:0] ethertype_fu_158;
wire   [15:0] ethertype_2_fu_534_p4;
wire   [15:0] ethertype_1_fu_665_p4;
reg   [15:0] dport_fu_162;
wire   [15:0] dport_2_fu_465_p4;
wire   [15:0] dport_1_fu_514_p4;
reg   [15:0] meta_seq_fu_166;
wire   [15:0] meta_seq_2_fu_427_p4;
wire   [15:0] meta_seq_1_fu_442_p4;
reg   [15:0] meta_chanspec_fu_170;
wire   [15:0] meta_chanspec_2_fu_392_p4;
wire   [15:0] meta_chanspec_1_fu_407_p4;
reg   [1:0] phase_fu_174;
reg   [0:0] keep_fu_178;
wire   [0:0] and_ln41_1_fu_498_p2;
reg    ap_block_pp0_stage0_01001;
wire    ap_block_pp0_stage0_01001_grp0;
wire   [0:0] icmp_ln41_1_fu_481_p2;
wire   [0:0] icmp_ln41_2_fu_487_p2;
wire   [0:0] and_ln41_fu_492_p2;
wire   [0:0] icmp_ln41_fu_475_p2;
wire   [7:0] tmp_1_fu_558_p4;
wire   [0:0] icmp_ln51_1_fu_568_p2;
wire   [0:0] icmp_ln51_fu_552_p2;
wire   [0:0] and_ln51_fu_574_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_547;
reg    ap_condition_551;
reg    ap_condition_555;
reg    ap_condition_559;
reg    ap_condition_562;
reg    ap_condition_565;
reg    ap_condition_570;
reg    ap_condition_573;
reg    ap_condition_576;
reg    ap_condition_581;
reg    ap_condition_585;
reg    ap_condition_588;
reg    ap_condition_591;
reg    ap_condition_594;
reg    ap_condition_598;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 idx_fu_126 = 16'd0;
#0 b2_fu_130 = 8'd0;
#0 b1_fu_134 = 8'd0;
#0 b0_fu_138 = 8'd0;
#0 ip_proto_fu_142 = 8'd0;
#0 meta_rssi_fu_146 = 8'd0;
#0 meta_core_spatial_fu_150 = 8'd0;
#0 n_sub_fu_154 = 16'd0;
#0 ethertype_fu_158 = 16'd0;
#0 dport_fu_162 = 16'd0;
#0 meta_seq_fu_166 = 16'd0;
#0 meta_chanspec_fu_170 = 16'd0;
#0 phase_fu_174 = 2'd0;
#0 keep_fu_178 = 1'd0;
#0 ap_done_reg = 1'b0;
end

csi_udp_parser_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready == 1'b0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            b0_fu_138 <= 8'd0;
        end else if ((1'b1 == ap_condition_547)) begin
            b0_fu_138 <= rx_TDATA;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            b1_fu_134 <= 8'd0;
        end else if ((1'b1 == ap_condition_551)) begin
            b1_fu_134 <= rx_TDATA;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            b2_fu_130 <= 8'd0;
        end else if ((1'b1 == ap_condition_555)) begin
            b2_fu_130 <= rx_TDATA;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            dport_fu_162 <= 16'd0;
        end else if ((1'b1 == ap_condition_562)) begin
            dport_fu_162 <= dport_1_fu_514_p4;
        end else if ((1'b1 == ap_condition_559)) begin
            dport_fu_162 <= dport_2_fu_465_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ethertype_fu_158 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln35_fu_362_p2 == 1'd1))) begin
            ethertype_fu_158 <= ethertype_1_fu_665_p4;
        end else if ((1'b1 == ap_condition_565)) begin
            ethertype_fu_158 <= ethertype_2_fu_534_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            idx_fu_126 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (beat_last_fu_358_p1 == 1'd0))) begin
            idx_fu_126 <= idx_2_fu_348_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ip_proto_fu_142 <= 8'd0;
        end else if ((1'b1 == ap_condition_570)) begin
            ip_proto_fu_142 <= rx_TDATA;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((~(idx_1_load_fu_342_p1 == 16'd57) & ~(idx_1_load_fu_342_p1 == 16'd56) & ~(idx_1_load_fu_342_p1 == 16'd54) & ~(idx_1_load_fu_342_p1 == 16'd53) & ~(idx_1_load_fu_342_p1 == 16'd52) & ~(idx_1_load_fu_342_p1 == 16'd44) & ~(idx_1_load_fu_342_p1 == 16'd37) & ~(idx_1_load_fu_342_p1 == 16'd36) & ~(idx_1_load_fu_342_p1 == 16'd23) & ~(idx_1_load_fu_342_p1 == 16'd13) & (1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln51_1_fu_580_p2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (phase_load_load_fu_586_p1 == 2'd3) & (icmp_ln35_fu_362_p2 == 1'd0)) | (~(idx_1_load_fu_342_p1 == 16'd57) & ~(idx_1_load_fu_342_p1 == 16'd56) & ~(idx_1_load_fu_342_p1 == 16'd54) & ~(idx_1_load_fu_342_p1 == 16'd53) & ~(idx_1_load_fu_342_p1 == 16'd52) & ~(idx_1_load_fu_342_p1 == 16'd44) & ~(idx_1_load_fu_342_p1 == 16'd37) & ~(idx_1_load_fu_342_p1 == 16'd36) & ~(idx_1_load_fu_342_p1 == 16'd23) & ~(idx_1_load_fu_342_p1 == 16'd13) & (1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln51_1_fu_580_p2) & (ap_enable_reg_pp0_iter1 
    == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (phase_load_load_fu_586_p1 == 2'd0) & (icmp_ln35_fu_362_p2 == 1'd0)) | (~(idx_1_load_fu_342_p1 == 16'd57) & ~(idx_1_load_fu_342_p1 == 16'd56) & ~(idx_1_load_fu_342_p1 == 16'd54) & ~(idx_1_load_fu_342_p1 == 16'd53) & ~(idx_1_load_fu_342_p1 == 16'd52) & ~(idx_1_load_fu_342_p1 == 16'd44) & ~(idx_1_load_fu_342_p1 == 16'd37) & ~(idx_1_load_fu_342_p1 == 16'd36) & ~(idx_1_load_fu_342_p1 == 16'd23) & ~(idx_1_load_fu_342_p1 == 16'd13) & (1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln51_1_fu_580_p2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (phase_load_load_fu_586_p1 == 2'd1) & (icmp_ln35_fu_362_p2 == 1'd0)) | (~(idx_1_load_fu_342_p1 == 16'd57) & ~(idx_1_load_fu_342_p1 == 16'd56) & ~(idx_1_load_fu_342_p1 == 16'd54) & ~(idx_1_load_fu_342_p1 == 16'd53) & ~(idx_1_load_fu_342_p1 == 16'd52) & ~(idx_1_load_fu_342_p1 == 16'd44) & ~(idx_1_load_fu_342_p1 == 16'd37) & ~(idx_1_load_fu_342_p1 == 16'd36) & ~(idx_1_load_fu_342_p1 == 16'd23) & ~(idx_1_load_fu_342_p1 
    == 16'd13) & (1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln51_1_fu_580_p2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (phase_load_load_fu_586_p1 == 2'd2) & (icmp_ln35_fu_362_p2 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        keep_fu_178 <= 1'd1;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln35_fu_362_p2 == 1'd0) & (idx_1_load_fu_342_p1 == 16'd37))) begin
        keep_fu_178 <= and_ln41_1_fu_498_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            meta_chanspec_fu_170 <= 16'd0;
        end else if ((1'b1 == ap_condition_576)) begin
            meta_chanspec_fu_170 <= meta_chanspec_1_fu_407_p4;
        end else if ((1'b1 == ap_condition_573)) begin
            meta_chanspec_fu_170 <= meta_chanspec_2_fu_392_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_585)) begin
            meta_core_spatial_fu_150 <= 8'd0;
        end else if ((1'b1 == ap_condition_581)) begin
            meta_core_spatial_fu_150 <= rx_TDATA;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_585)) begin
            meta_rssi_fu_146 <= 8'd0;
        end else if ((1'b1 == ap_condition_588)) begin
            meta_rssi_fu_146 <= rx_TDATA;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            meta_seq_fu_166 <= 16'd0;
        end else if ((1'b1 == ap_condition_594)) begin
            meta_seq_fu_166 <= meta_seq_1_fu_442_p4;
        end else if ((1'b1 == ap_condition_591)) begin
            meta_seq_fu_166 <= meta_seq_2_fu_427_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            n_sub_fu_154 <= 16'd0;
        end else if ((1'b1 == ap_condition_598)) begin
            n_sub_fu_154 <= n_sub_3_fu_644_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((~(idx_1_load_fu_342_p1 == 16'd57) & ~(idx_1_load_fu_342_p1 == 16'd56) & ~(idx_1_load_fu_342_p1 == 16'd54) & ~(idx_1_load_fu_342_p1 == 16'd53) & ~(idx_1_load_fu_342_p1 == 16'd52) & ~(idx_1_load_fu_342_p1 == 16'd44) & ~(idx_1_load_fu_342_p1 == 16'd37) & ~(idx_1_load_fu_342_p1 == 16'd36) & ~(idx_1_load_fu_342_p1 == 16'd23) & ~(idx_1_load_fu_342_p1 == 16'd13) & (1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln51_1_fu_580_p2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (phase_load_load_fu_586_p1 == 2'd3) & (icmp_ln35_fu_362_p2 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        phase_fu_174 <= 2'd0;
    end else if ((~(idx_1_load_fu_342_p1 == 16'd57) & ~(idx_1_load_fu_342_p1 == 16'd56) & ~(idx_1_load_fu_342_p1 == 16'd54) & ~(idx_1_load_fu_342_p1 == 16'd53) & ~(idx_1_load_fu_342_p1 == 16'd52) & ~(idx_1_load_fu_342_p1 == 16'd44) & ~(idx_1_load_fu_342_p1 == 16'd37) & ~(idx_1_load_fu_342_p1 == 16'd36) & ~(idx_1_load_fu_342_p1 == 16'd23) & ~(idx_1_load_fu_342_p1 == 16'd13) & (1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln51_1_fu_580_p2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (phase_load_load_fu_586_p1 == 2'd0) & (icmp_ln35_fu_362_p2 == 1'd0))) begin
        phase_fu_174 <= 2'd1;
    end else if ((~(idx_1_load_fu_342_p1 == 16'd57) & ~(idx_1_load_fu_342_p1 == 16'd56) & ~(idx_1_load_fu_342_p1 == 16'd54) & ~(idx_1_load_fu_342_p1 == 16'd53) & ~(idx_1_load_fu_342_p1 == 16'd52) & ~(idx_1_load_fu_342_p1 == 16'd44) & ~(idx_1_load_fu_342_p1 == 16'd37) & ~(idx_1_load_fu_342_p1 == 16'd36) & ~(idx_1_load_fu_342_p1 == 16'd23) & ~(idx_1_load_fu_342_p1 == 16'd13) & (1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln51_1_fu_580_p2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (phase_load_load_fu_586_p1 == 2'd1) & (icmp_ln35_fu_362_p2 == 1'd0))) begin
        phase_fu_174 <= 2'd2;
    end else if ((~(idx_1_load_fu_342_p1 == 16'd57) & ~(idx_1_load_fu_342_p1 == 16'd56) & ~(idx_1_load_fu_342_p1 == 16'd54) & ~(idx_1_load_fu_342_p1 == 16'd53) & ~(idx_1_load_fu_342_p1 == 16'd52) & ~(idx_1_load_fu_342_p1 == 16'd44) & ~(idx_1_load_fu_342_p1 == 16'd37) & ~(idx_1_load_fu_342_p1 == 16'd36) & ~(idx_1_load_fu_342_p1 == 16'd23) & ~(idx_1_load_fu_342_p1 == 16'd13) & (1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln51_1_fu_580_p2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (phase_load_load_fu_586_p1 == 2'd2) & (icmp_ln35_fu_362_p2 == 1'd0))) begin
        phase_fu_174 <= 2'd3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln51_1_reg_866 <= and_ln51_1_fu_580_p2;
        beat_data_reg_852 <= rx_TDATA;
        beat_last_reg_857 <= rx_TLAST;
        icmp_ln35_reg_862 <= icmp_ln35_fu_362_p2;
        idx_1_reg_848 <= idx_fu_126;
        phase_load_reg_870 <= phase_fu_174;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (beat_last_fu_358_p1 == 1'd1))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op128_write_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        csi_out_TDATA_blk_n = csi_out_TREADY;
    end else begin
        csi_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op128_write_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        csi_out_TVALID = 1'b1;
    end else begin
        csi_out_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (beat_last_reg_857 == 1'd1))) begin
        keep_1_out_ap_vld = 1'b1;
    end else begin
        keep_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (beat_last_reg_857 == 1'd1))) begin
        meta_chanspec_3_out_ap_vld = 1'b1;
    end else begin
        meta_chanspec_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (beat_last_reg_857 == 1'd1))) begin
        meta_core_spatial_1_out_ap_vld = 1'b1;
    end else begin
        meta_core_spatial_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (beat_last_reg_857 == 1'd1))) begin
        meta_rssi_2_out_ap_vld = 1'b1;
    end else begin
        meta_rssi_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (beat_last_reg_857 == 1'd1))) begin
        meta_seq_3_out_ap_vld = 1'b1;
    end else begin
        meta_seq_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (beat_last_reg_857 == 1'd1))) begin
        n_sub_3_out_ap_vld = 1'b1;
    end else begin
        n_sub_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        rx_TDATA_blk_n = rx_TVALID;
    end else begin
        rx_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        rx_TREADY = 1'b1;
    end else begin
        rx_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign and_ln41_1_fu_498_p2 = (icmp_ln41_fu_475_p2 & and_ln41_fu_492_p2);

assign and_ln41_fu_492_p2 = (icmp_ln41_2_fu_487_p2 & icmp_ln41_1_fu_481_p2);

assign and_ln51_1_fu_580_p2 = (keep_fu_178 & and_ln51_fu_574_p2);

assign and_ln51_fu_574_p2 = (icmp_ln51_fu_552_p2 & icmp_ln51_1_fu_568_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)));
end

assign ap_block_pp0_stage0_01001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (rx_TVALID == 1'b0);
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((ap_predicate_op128_write_state3 == 1'b1) & (csi_out_TREADY == 1'b0));
end

always @ (*) begin
    ap_condition_547 = (~(idx_1_load_fu_342_p1 == 16'd57) & ~(idx_1_load_fu_342_p1 == 16'd56) & ~(idx_1_load_fu_342_p1 == 16'd54) & ~(idx_1_load_fu_342_p1 == 16'd53) & ~(idx_1_load_fu_342_p1 == 16'd52) & ~(idx_1_load_fu_342_p1 == 16'd44) & ~(idx_1_load_fu_342_p1 == 16'd37) & ~(idx_1_load_fu_342_p1 == 16'd36) & ~(idx_1_load_fu_342_p1 == 16'd23) & ~(idx_1_load_fu_342_p1 == 16'd13) & (1'd1 == and_ln51_1_fu_580_p2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (phase_load_load_fu_586_p1 == 2'd0) & (icmp_ln35_fu_362_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_551 = (~(idx_1_load_fu_342_p1 == 16'd57) & ~(idx_1_load_fu_342_p1 == 16'd56) & ~(idx_1_load_fu_342_p1 == 16'd54) & ~(idx_1_load_fu_342_p1 == 16'd53) & ~(idx_1_load_fu_342_p1 == 16'd52) & ~(idx_1_load_fu_342_p1 == 16'd44) & ~(idx_1_load_fu_342_p1 == 16'd37) & ~(idx_1_load_fu_342_p1 == 16'd36) & ~(idx_1_load_fu_342_p1 == 16'd23) & ~(idx_1_load_fu_342_p1 == 16'd13) & (1'd1 == and_ln51_1_fu_580_p2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (phase_load_load_fu_586_p1 == 2'd1) & (icmp_ln35_fu_362_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_555 = (~(idx_1_load_fu_342_p1 == 16'd57) & ~(idx_1_load_fu_342_p1 == 16'd56) & ~(idx_1_load_fu_342_p1 == 16'd54) & ~(idx_1_load_fu_342_p1 == 16'd53) & ~(idx_1_load_fu_342_p1 == 16'd52) & ~(idx_1_load_fu_342_p1 == 16'd44) & ~(idx_1_load_fu_342_p1 == 16'd37) & ~(idx_1_load_fu_342_p1 == 16'd36) & ~(idx_1_load_fu_342_p1 == 16'd23) & ~(idx_1_load_fu_342_p1 == 16'd13) & (1'd1 == and_ln51_1_fu_580_p2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (phase_load_load_fu_586_p1 == 2'd2) & (icmp_ln35_fu_362_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_559 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln35_fu_362_p2 == 1'd0) & (idx_1_load_fu_342_p1 == 16'd37));
end

always @ (*) begin
    ap_condition_562 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln35_fu_362_p2 == 1'd0) & (idx_1_load_fu_342_p1 == 16'd36));
end

always @ (*) begin
    ap_condition_565 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln35_fu_362_p2 == 1'd0) & (idx_1_load_fu_342_p1 == 16'd13));
end

always @ (*) begin
    ap_condition_570 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln35_fu_362_p2 == 1'd0) & (idx_1_load_fu_342_p1 == 16'd23));
end

always @ (*) begin
    ap_condition_573 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln35_fu_362_p2 == 1'd0) & (idx_1_load_fu_342_p1 == 16'd57));
end

always @ (*) begin
    ap_condition_576 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln35_fu_362_p2 == 1'd0) & (idx_1_load_fu_342_p1 == 16'd56));
end

always @ (*) begin
    ap_condition_581 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln35_fu_362_p2 == 1'd0) & (idx_1_load_fu_342_p1 == 16'd54));
end

always @ (*) begin
    ap_condition_585 = ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_init == 1'b1));
end

always @ (*) begin
    ap_condition_588 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln35_fu_362_p2 == 1'd0) & (idx_1_load_fu_342_p1 == 16'd44));
end

always @ (*) begin
    ap_condition_591 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln35_fu_362_p2 == 1'd0) & (idx_1_load_fu_342_p1 == 16'd53));
end

always @ (*) begin
    ap_condition_594 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln35_fu_362_p2 == 1'd0) & (idx_1_load_fu_342_p1 == 16'd52));
end

always @ (*) begin
    ap_condition_598 = (~(idx_1_load_fu_342_p1 == 16'd57) & ~(idx_1_load_fu_342_p1 == 16'd56) & ~(idx_1_load_fu_342_p1 == 16'd54) & ~(idx_1_load_fu_342_p1 == 16'd53) & ~(idx_1_load_fu_342_p1 == 16'd52) & ~(idx_1_load_fu_342_p1 == 16'd44) & ~(idx_1_load_fu_342_p1 == 16'd37) & ~(idx_1_load_fu_342_p1 == 16'd36) & ~(idx_1_load_fu_342_p1 == 16'd23) & ~(idx_1_load_fu_342_p1 == 16'd13) & (1'd1 == and_ln51_1_fu_580_p2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (phase_load_load_fu_586_p1 == 2'd3) & (icmp_ln35_fu_362_p2 == 1'd0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

always @ (*) begin
    ap_predicate_op128_write_state3 = (~(idx_1_reg_848 == 16'd57) & ~(idx_1_reg_848 == 16'd56) & ~(idx_1_reg_848 == 16'd54) & ~(idx_1_reg_848 == 16'd53) & ~(idx_1_reg_848 == 16'd52) & ~(idx_1_reg_848 == 16'd44) & ~(idx_1_reg_848 == 16'd37) & ~(idx_1_reg_848 == 16'd36) & ~(idx_1_reg_848 == 16'd23) & ~(idx_1_reg_848 == 16'd13) & (phase_load_reg_870 == 2'd3) & (1'd1 == and_ln51_1_reg_866) & (icmp_ln35_reg_862 == 1'd0));
end

assign ap_ready = ap_ready_sig;

assign beat_last_fu_358_p1 = rx_TLAST;

assign csi_out_TDATA = {{{{beat_data_reg_852}, {b2_fu_130}}, {b1_fu_134}}, {b0_fu_138}};

assign csi_out_TKEEP = 4'd15;

assign csi_out_TLAST = beat_last_reg_857;

assign csi_out_TSTRB = 4'd15;

assign dport_1_fu_514_p4 = {{rx_TDATA}, {dport_fu_162[7:0]}};

assign dport_2_fu_465_p4 = {{dport_fu_162[15:8]}, {rx_TDATA}};

assign ethertype_1_fu_665_p4 = {{rx_TDATA}, {ethertype_fu_158[7:0]}};

assign ethertype_2_fu_534_p4 = {{ethertype_fu_158[15:8]}, {rx_TDATA}};

assign icmp_ln35_fu_362_p2 = ((idx_fu_126 == 16'd12) ? 1'b1 : 1'b0);

assign icmp_ln41_1_fu_481_p2 = ((ip_proto_fu_142 == 8'd17) ? 1'b1 : 1'b0);

assign icmp_ln41_2_fu_487_p2 = ((dport_2_fu_465_p4 == udp_port) ? 1'b1 : 1'b0);

assign icmp_ln41_fu_475_p2 = ((ethertype_fu_158 == 16'd2048) ? 1'b1 : 1'b0);

assign icmp_ln51_1_fu_568_p2 = ((tmp_1_fu_558_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_552_p2 = ((idx_fu_126 > 16'd59) ? 1'b1 : 1'b0);

assign idx_1_load_fu_342_p1 = idx_fu_126;

assign idx_2_fu_348_p2 = (idx_fu_126 + 16'd1);

assign keep_1_out = keep_fu_178;

assign meta_chanspec_1_fu_407_p4 = {{meta_chanspec_fu_170[15:8]}, {rx_TDATA}};

assign meta_chanspec_2_fu_392_p4 = {{rx_TDATA}, {meta_chanspec_fu_170[7:0]}};

assign meta_chanspec_3_out = meta_chanspec_fu_170;

assign meta_core_spatial_1_out = meta_core_spatial_fu_150;

assign meta_rssi_2_out = meta_rssi_fu_146;

assign meta_seq_1_fu_442_p4 = {{meta_seq_fu_166[15:8]}, {rx_TDATA}};

assign meta_seq_2_fu_427_p4 = {{rx_TDATA}, {meta_seq_fu_166[7:0]}};

assign meta_seq_3_out = meta_seq_fu_166;

assign n_sub_3_fu_644_p2 = (n_sub_fu_154 + 16'd1);

assign n_sub_3_out = n_sub_fu_154;

assign phase_load_load_fu_586_p1 = phase_fu_174;

assign tmp_1_fu_558_p4 = {{n_sub_fu_154[15:8]}};

endmodule //csi_udp_parser_csi_udp_parser_Pipeline_parse
