-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity csi_udp_parser_csi_udp_parser_Pipeline_parse is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    rx_TVALID : IN STD_LOGIC;
    csi_out_TREADY : IN STD_LOGIC;
    rx_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    rx_TREADY : OUT STD_LOGIC;
    rx_TKEEP : IN STD_LOGIC_VECTOR (0 downto 0);
    rx_TSTRB : IN STD_LOGIC_VECTOR (0 downto 0);
    rx_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    udp_port : IN STD_LOGIC_VECTOR (15 downto 0);
    csi_out_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    csi_out_TVALID : OUT STD_LOGIC;
    csi_out_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    csi_out_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    csi_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    meta_rssi_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    meta_rssi_out_ap_vld : OUT STD_LOGIC;
    meta_seq_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    meta_seq_out_ap_vld : OUT STD_LOGIC;
    meta_core_spatial_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    meta_core_spatial_out_ap_vld : OUT STD_LOGIC;
    meta_chanspec_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    meta_chanspec_out_ap_vld : OUT STD_LOGIC;
    n_sub_3_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    n_sub_3_out_ap_vld : OUT STD_LOGIC;
    keep_1_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    keep_1_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of csi_udp_parser_csi_udp_parser_Pipeline_parse is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv16_D : STD_LOGIC_VECTOR (15 downto 0) := "0000000000001101";
    constant ap_const_lv16_17 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000010111";
    constant ap_const_lv16_24 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000100100";
    constant ap_const_lv16_25 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000100101";
    constant ap_const_lv16_2C : STD_LOGIC_VECTOR (15 downto 0) := "0000000000101100";
    constant ap_const_lv16_34 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000110100";
    constant ap_const_lv16_35 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000110101";
    constant ap_const_lv16_36 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000110110";
    constant ap_const_lv16_38 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000111000";
    constant ap_const_lv16_39 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000111001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv16_C : STD_LOGIC_VECTOR (15 downto 0) := "0000000000001100";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv16_800 : STD_LOGIC_VECTOR (15 downto 0) := "0000100000000000";
    constant ap_const_lv8_11 : STD_LOGIC_VECTOR (7 downto 0) := "00010001";
    constant ap_const_lv16_3B : STD_LOGIC_VECTOR (15 downto 0) := "0000000000111011";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal icmp_ln35_reg_862 : STD_LOGIC_VECTOR (0 downto 0);
    signal idx_1_reg_848 : STD_LOGIC_VECTOR (15 downto 0);
    signal and_ln51_1_reg_866 : STD_LOGIC_VECTOR (0 downto 0);
    signal phase_load_reg_870 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_predicate_op128_write_state3 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal beat_last_fu_358_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal rx_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal csi_out_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal idx_1_load_fu_342_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal beat_data_reg_852 : STD_LOGIC_VECTOR (7 downto 0);
    signal beat_last_reg_857 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln35_fu_362_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln51_1_fu_580_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal phase_load_load_fu_586_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal idx_fu_126 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal idx_2_fu_348_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal b2_fu_130 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal b1_fu_134 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal b0_fu_138 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal n_sub_fu_142 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal n_sub_3_fu_644_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_block_pp0_stage0_grp0 : BOOLEAN;
    signal ip_proto_fu_146 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_0_0_0589767_fu_150 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_0_0_0589778_fu_154 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal dport_fu_158 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal dport_2_fu_465_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal dport_1_fu_514_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ethertype_fu_162 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal ethertype_2_fu_534_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ethertype_1_fu_665_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal empty_fu_166 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal tmp_3_fu_392_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_2_fu_407_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal empty_20_fu_170 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal tmp_1_fu_427_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_fu_442_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal phase_fu_174 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal keep_fu_178 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal and_ln41_1_fu_498_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp0 : BOOLEAN;
    signal icmp_ln41_1_fu_481_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln41_2_fu_487_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln41_fu_492_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln41_fu_475_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_558_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln51_1_fu_568_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_fu_552_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln51_fu_574_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_547 : BOOLEAN;
    signal ap_condition_551 : BOOLEAN;
    signal ap_condition_555 : BOOLEAN;
    signal ap_condition_559 : BOOLEAN;
    signal ap_condition_562 : BOOLEAN;
    signal ap_condition_565 : BOOLEAN;
    signal ap_condition_568 : BOOLEAN;
    signal ap_condition_571 : BOOLEAN;
    signal ap_condition_574 : BOOLEAN;
    signal ap_condition_577 : BOOLEAN;
    signal ap_condition_582 : BOOLEAN;
    signal ap_condition_586 : BOOLEAN;
    signal ap_condition_591 : BOOLEAN;
    signal ap_condition_595 : BOOLEAN;
    signal ap_condition_598 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component csi_udp_parser_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component csi_udp_parser_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0)) then 
                    ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter2_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready = ap_const_logic_0))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
            end if; 
        end if;
    end process;

    b0_fu_138_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    b0_fu_138 <= ap_const_lv8_0;
                elsif ((ap_const_boolean_1 = ap_condition_547)) then 
                    b0_fu_138 <= rx_TDATA;
                end if;
            end if; 
        end if;
    end process;

    b1_fu_134_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    b1_fu_134 <= ap_const_lv8_0;
                elsif ((ap_const_boolean_1 = ap_condition_551)) then 
                    b1_fu_134 <= rx_TDATA;
                end if;
            end if; 
        end if;
    end process;

    b2_fu_130_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    b2_fu_130 <= ap_const_lv8_0;
                elsif ((ap_const_boolean_1 = ap_condition_555)) then 
                    b2_fu_130 <= rx_TDATA;
                end if;
            end if; 
        end if;
    end process;

    dport_fu_158_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    dport_fu_158 <= ap_const_lv16_0;
                elsif ((ap_const_boolean_1 = ap_condition_562)) then 
                    dport_fu_158 <= dport_1_fu_514_p4;
                elsif ((ap_const_boolean_1 = ap_condition_559)) then 
                    dport_fu_158 <= dport_2_fu_465_p4;
                end if;
            end if; 
        end if;
    end process;

    empty_20_fu_170_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    empty_20_fu_170 <= ap_const_lv16_0;
                elsif ((ap_const_boolean_1 = ap_condition_568)) then 
                    empty_20_fu_170 <= tmp_fu_442_p4;
                elsif ((ap_const_boolean_1 = ap_condition_565)) then 
                    empty_20_fu_170 <= tmp_1_fu_427_p4;
                end if;
            end if; 
        end if;
    end process;

    empty_fu_166_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    empty_fu_166 <= ap_const_lv16_0;
                elsif ((ap_const_boolean_1 = ap_condition_574)) then 
                    empty_fu_166 <= tmp_2_fu_407_p4;
                elsif ((ap_const_boolean_1 = ap_condition_571)) then 
                    empty_fu_166 <= tmp_3_fu_392_p4;
                end if;
            end if; 
        end if;
    end process;

    ethertype_fu_162_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    ethertype_fu_162 <= ap_const_lv16_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln35_fu_362_p2 = ap_const_lv1_1))) then 
                    ethertype_fu_162 <= ethertype_1_fu_665_p4;
                elsif ((ap_const_boolean_1 = ap_condition_577)) then 
                    ethertype_fu_162 <= ethertype_2_fu_534_p4;
                end if;
            end if; 
        end if;
    end process;

    idx_fu_126_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    idx_fu_126 <= ap_const_lv16_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (beat_last_fu_358_p1 = ap_const_lv1_0))) then 
                    idx_fu_126 <= idx_2_fu_348_p2;
                end if;
            end if; 
        end if;
    end process;

    ip_proto_fu_146_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    ip_proto_fu_146 <= ap_const_lv8_0;
                elsif ((ap_const_boolean_1 = ap_condition_582)) then 
                    ip_proto_fu_146 <= rx_TDATA;
                end if;
            end if; 
        end if;
    end process;

    keep_fu_178_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not((idx_1_load_fu_342_p1 = ap_const_lv16_39)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_38)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_36)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_35)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_34)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_2C)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_25)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_24)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_17)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_D)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln51_1_fu_580_p2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (phase_load_load_fu_586_p1 = ap_const_lv2_3) and (icmp_ln35_fu_362_p2 = ap_const_lv1_0)) or (not((idx_1_load_fu_342_p1 = ap_const_lv16_39)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_38)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_36)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_35)) and not((idx_1_load_fu_342_p1 
    = ap_const_lv16_34)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_2C)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_25)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_24)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_17)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_D)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln51_1_fu_580_p2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (phase_load_load_fu_586_p1 = ap_const_lv2_0) and (icmp_ln35_fu_362_p2 = ap_const_lv1_0)) or (not((idx_1_load_fu_342_p1 = ap_const_lv16_39)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_38)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_36)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_35)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_34)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_2C)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_25)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_24)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_17)) and not((idx_1_load_fu_342_p1 
    = ap_const_lv16_D)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln51_1_fu_580_p2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (phase_load_load_fu_586_p1 = ap_const_lv2_1) and (icmp_ln35_fu_362_p2 = ap_const_lv1_0)) or (not((idx_1_load_fu_342_p1 = ap_const_lv16_39)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_38)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_36)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_35)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_34)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_2C)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_25)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_24)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_17)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_D)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln51_1_fu_580_p2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (phase_load_load_fu_586_p1 
    = ap_const_lv2_2) and (icmp_ln35_fu_362_p2 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
                keep_fu_178 <= ap_const_lv1_1;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln35_fu_362_p2 = ap_const_lv1_0) and (idx_1_load_fu_342_p1 = ap_const_lv16_25))) then 
                keep_fu_178 <= and_ln41_1_fu_498_p2;
            end if; 
        end if;
    end process;

    n_sub_fu_142_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    n_sub_fu_142 <= ap_const_lv16_0;
                elsif ((ap_const_boolean_1 = ap_condition_586)) then 
                    n_sub_fu_142 <= n_sub_3_fu_644_p2;
                end if;
            end if; 
        end if;
    end process;

    p_0_0_0589767_fu_150_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                if ((ap_const_boolean_1 = ap_condition_595)) then 
                    p_0_0_0589767_fu_150 <= ap_const_lv8_0;
                elsif ((ap_const_boolean_1 = ap_condition_591)) then 
                    p_0_0_0589767_fu_150 <= rx_TDATA;
                end if;
            end if; 
        end if;
    end process;

    p_0_0_0589778_fu_154_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                if ((ap_const_boolean_1 = ap_condition_595)) then 
                    p_0_0_0589778_fu_154 <= ap_const_lv8_0;
                elsif ((ap_const_boolean_1 = ap_condition_598)) then 
                    p_0_0_0589778_fu_154 <= rx_TDATA;
                end if;
            end if; 
        end if;
    end process;

    phase_fu_174_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not((idx_1_load_fu_342_p1 = ap_const_lv16_39)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_38)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_36)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_35)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_34)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_2C)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_25)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_24)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_17)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_D)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln51_1_fu_580_p2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (phase_load_load_fu_586_p1 = ap_const_lv2_3) and (icmp_ln35_fu_362_p2 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
                phase_fu_174 <= ap_const_lv2_0;
            elsif ((not((idx_1_load_fu_342_p1 = ap_const_lv16_39)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_38)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_36)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_35)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_34)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_2C)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_25)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_24)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_17)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_D)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln51_1_fu_580_p2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (phase_load_load_fu_586_p1 = ap_const_lv2_0) and (icmp_ln35_fu_362_p2 = ap_const_lv1_0))) then 
                phase_fu_174 <= ap_const_lv2_1;
            elsif ((not((idx_1_load_fu_342_p1 = ap_const_lv16_39)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_38)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_36)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_35)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_34)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_2C)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_25)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_24)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_17)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_D)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln51_1_fu_580_p2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (phase_load_load_fu_586_p1 = ap_const_lv2_1) and (icmp_ln35_fu_362_p2 = ap_const_lv1_0))) then 
                phase_fu_174 <= ap_const_lv2_2;
            elsif ((not((idx_1_load_fu_342_p1 = ap_const_lv16_39)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_38)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_36)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_35)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_34)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_2C)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_25)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_24)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_17)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_D)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln51_1_fu_580_p2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (phase_load_load_fu_586_p1 = ap_const_lv2_2) and (icmp_ln35_fu_362_p2 = ap_const_lv1_0))) then 
                phase_fu_174 <= ap_const_lv2_3;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                and_ln51_1_reg_866 <= and_ln51_1_fu_580_p2;
                beat_data_reg_852 <= rx_TDATA;
                beat_last_reg_857 <= rx_TLAST;
                icmp_ln35_reg_862 <= icmp_ln35_fu_362_p2;
                idx_1_reg_848 <= idx_fu_126;
                phase_load_reg_870 <= phase_fu_174;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    and_ln41_1_fu_498_p2 <= (icmp_ln41_fu_475_p2 and and_ln41_fu_492_p2);
    and_ln41_fu_492_p2 <= (icmp_ln41_2_fu_487_p2 and icmp_ln41_1_fu_481_p2);
    and_ln51_1_fu_580_p2 <= (keep_fu_178 and and_ln51_fu_574_p2);
    and_ln51_fu_574_p2 <= (icmp_ln51_fu_552_p2 and icmp_ln51_1_fu_568_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_block_state2_pp0_stage0_iter1, ap_block_state3_pp0_stage0_iter2)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)));
    end process;

        ap_block_pp0_stage0_01001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_block_state2_pp0_stage0_iter1, ap_block_state3_pp0_stage0_iter2)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_block_state2_pp0_stage0_iter1, ap_block_state3_pp0_stage0_iter2)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_pp0_stage0_iter1_assign_proc : process(rx_TVALID)
    begin
                ap_block_state2_pp0_stage0_iter1 <= (rx_TVALID = ap_const_logic_0);
    end process;


    ap_block_state3_pp0_stage0_iter2_assign_proc : process(csi_out_TREADY, ap_predicate_op128_write_state3)
    begin
                ap_block_state3_pp0_stage0_iter2 <= ((ap_predicate_op128_write_state3 = ap_const_boolean_1) and (csi_out_TREADY = ap_const_logic_0));
    end process;


    ap_condition_547_assign_proc : process(ap_enable_reg_pp0_iter1, idx_1_load_fu_342_p1, icmp_ln35_fu_362_p2, and_ln51_1_fu_580_p2, phase_load_load_fu_586_p1)
    begin
                ap_condition_547 <= (not((idx_1_load_fu_342_p1 = ap_const_lv16_39)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_38)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_36)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_35)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_34)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_2C)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_25)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_24)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_17)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_D)) and (ap_const_lv1_1 = and_ln51_1_fu_580_p2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (phase_load_load_fu_586_p1 = ap_const_lv2_0) and (icmp_ln35_fu_362_p2 = ap_const_lv1_0));
    end process;


    ap_condition_551_assign_proc : process(ap_enable_reg_pp0_iter1, idx_1_load_fu_342_p1, icmp_ln35_fu_362_p2, and_ln51_1_fu_580_p2, phase_load_load_fu_586_p1)
    begin
                ap_condition_551 <= (not((idx_1_load_fu_342_p1 = ap_const_lv16_39)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_38)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_36)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_35)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_34)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_2C)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_25)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_24)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_17)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_D)) and (ap_const_lv1_1 = and_ln51_1_fu_580_p2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (phase_load_load_fu_586_p1 = ap_const_lv2_1) and (icmp_ln35_fu_362_p2 = ap_const_lv1_0));
    end process;


    ap_condition_555_assign_proc : process(ap_enable_reg_pp0_iter1, idx_1_load_fu_342_p1, icmp_ln35_fu_362_p2, and_ln51_1_fu_580_p2, phase_load_load_fu_586_p1)
    begin
                ap_condition_555 <= (not((idx_1_load_fu_342_p1 = ap_const_lv16_39)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_38)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_36)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_35)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_34)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_2C)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_25)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_24)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_17)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_D)) and (ap_const_lv1_1 = and_ln51_1_fu_580_p2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (phase_load_load_fu_586_p1 = ap_const_lv2_2) and (icmp_ln35_fu_362_p2 = ap_const_lv1_0));
    end process;


    ap_condition_559_assign_proc : process(ap_enable_reg_pp0_iter1, idx_1_load_fu_342_p1, icmp_ln35_fu_362_p2)
    begin
                ap_condition_559 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln35_fu_362_p2 = ap_const_lv1_0) and (idx_1_load_fu_342_p1 = ap_const_lv16_25));
    end process;


    ap_condition_562_assign_proc : process(ap_enable_reg_pp0_iter1, idx_1_load_fu_342_p1, icmp_ln35_fu_362_p2)
    begin
                ap_condition_562 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln35_fu_362_p2 = ap_const_lv1_0) and (idx_1_load_fu_342_p1 = ap_const_lv16_24));
    end process;


    ap_condition_565_assign_proc : process(ap_enable_reg_pp0_iter1, idx_1_load_fu_342_p1, icmp_ln35_fu_362_p2)
    begin
                ap_condition_565 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln35_fu_362_p2 = ap_const_lv1_0) and (idx_1_load_fu_342_p1 = ap_const_lv16_35));
    end process;


    ap_condition_568_assign_proc : process(ap_enable_reg_pp0_iter1, idx_1_load_fu_342_p1, icmp_ln35_fu_362_p2)
    begin
                ap_condition_568 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln35_fu_362_p2 = ap_const_lv1_0) and (idx_1_load_fu_342_p1 = ap_const_lv16_34));
    end process;


    ap_condition_571_assign_proc : process(ap_enable_reg_pp0_iter1, idx_1_load_fu_342_p1, icmp_ln35_fu_362_p2)
    begin
                ap_condition_571 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln35_fu_362_p2 = ap_const_lv1_0) and (idx_1_load_fu_342_p1 = ap_const_lv16_39));
    end process;


    ap_condition_574_assign_proc : process(ap_enable_reg_pp0_iter1, idx_1_load_fu_342_p1, icmp_ln35_fu_362_p2)
    begin
                ap_condition_574 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln35_fu_362_p2 = ap_const_lv1_0) and (idx_1_load_fu_342_p1 = ap_const_lv16_38));
    end process;


    ap_condition_577_assign_proc : process(ap_enable_reg_pp0_iter1, idx_1_load_fu_342_p1, icmp_ln35_fu_362_p2)
    begin
                ap_condition_577 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln35_fu_362_p2 = ap_const_lv1_0) and (idx_1_load_fu_342_p1 = ap_const_lv16_D));
    end process;


    ap_condition_582_assign_proc : process(ap_enable_reg_pp0_iter1, idx_1_load_fu_342_p1, icmp_ln35_fu_362_p2)
    begin
                ap_condition_582 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln35_fu_362_p2 = ap_const_lv1_0) and (idx_1_load_fu_342_p1 = ap_const_lv16_17));
    end process;


    ap_condition_586_assign_proc : process(ap_enable_reg_pp0_iter1, idx_1_load_fu_342_p1, icmp_ln35_fu_362_p2, and_ln51_1_fu_580_p2, phase_load_load_fu_586_p1)
    begin
                ap_condition_586 <= (not((idx_1_load_fu_342_p1 = ap_const_lv16_39)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_38)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_36)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_35)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_34)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_2C)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_25)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_24)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_17)) and not((idx_1_load_fu_342_p1 = ap_const_lv16_D)) and (ap_const_lv1_1 = and_ln51_1_fu_580_p2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (phase_load_load_fu_586_p1 = ap_const_lv2_3) and (icmp_ln35_fu_362_p2 = ap_const_lv1_0));
    end process;


    ap_condition_591_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, idx_1_load_fu_342_p1, icmp_ln35_fu_362_p2)
    begin
                ap_condition_591 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln35_fu_362_p2 = ap_const_lv1_0) and (idx_1_load_fu_342_p1 = ap_const_lv16_36));
    end process;


    ap_condition_595_assign_proc : process(ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, ap_loop_init)
    begin
                ap_condition_595 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_loop_init = ap_const_logic_1));
    end process;


    ap_condition_598_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, idx_1_load_fu_342_p1, icmp_ln35_fu_362_p2)
    begin
                ap_condition_598 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln35_fu_362_p2 = ap_const_lv1_0) and (idx_1_load_fu_342_p1 = ap_const_lv16_2C));
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, beat_last_fu_358_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (beat_last_fu_358_p1 = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter2_reg, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_predicate_op128_write_state3_assign_proc : process(icmp_ln35_reg_862, idx_1_reg_848, and_ln51_1_reg_866, phase_load_reg_870)
    begin
                ap_predicate_op128_write_state3 <= (not((idx_1_reg_848 = ap_const_lv16_39)) and not((idx_1_reg_848 = ap_const_lv16_38)) and not((idx_1_reg_848 = ap_const_lv16_36)) and not((idx_1_reg_848 = ap_const_lv16_35)) and not((idx_1_reg_848 = ap_const_lv16_34)) and not((idx_1_reg_848 = ap_const_lv16_2C)) and not((idx_1_reg_848 = ap_const_lv16_25)) and not((idx_1_reg_848 = ap_const_lv16_24)) and not((idx_1_reg_848 = ap_const_lv16_17)) and not((idx_1_reg_848 = ap_const_lv16_D)) and (phase_load_reg_870 = ap_const_lv2_3) and (ap_const_lv1_1 = and_ln51_1_reg_866) and (icmp_ln35_reg_862 = ap_const_lv1_0));
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    beat_last_fu_358_p1 <= rx_TLAST;
    csi_out_TDATA <= (((beat_data_reg_852 & b2_fu_130) & b1_fu_134) & b0_fu_138);

    csi_out_TDATA_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, csi_out_TREADY, ap_predicate_op128_write_state3, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op128_write_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            csi_out_TDATA_blk_n <= csi_out_TREADY;
        else 
            csi_out_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    csi_out_TKEEP <= ap_const_lv4_F;
    csi_out_TLAST <= beat_last_reg_857;
    csi_out_TSTRB <= ap_const_lv4_F;

    csi_out_TVALID_assign_proc : process(ap_enable_reg_pp0_iter2, ap_predicate_op128_write_state3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op128_write_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            csi_out_TVALID <= ap_const_logic_1;
        else 
            csi_out_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    dport_1_fu_514_p4 <= (rx_TDATA & dport_fu_158(7 downto 0));
    dport_2_fu_465_p4 <= (dport_fu_158(15 downto 8) & rx_TDATA);
    ethertype_1_fu_665_p4 <= (rx_TDATA & ethertype_fu_162(7 downto 0));
    ethertype_2_fu_534_p4 <= (ethertype_fu_162(15 downto 8) & rx_TDATA);
    icmp_ln35_fu_362_p2 <= "1" when (idx_fu_126 = ap_const_lv16_C) else "0";
    icmp_ln41_1_fu_481_p2 <= "1" when (ip_proto_fu_146 = ap_const_lv8_11) else "0";
    icmp_ln41_2_fu_487_p2 <= "1" when (dport_2_fu_465_p4 = udp_port) else "0";
    icmp_ln41_fu_475_p2 <= "1" when (ethertype_fu_162 = ap_const_lv16_800) else "0";
    icmp_ln51_1_fu_568_p2 <= "1" when (tmp_4_fu_558_p4 = ap_const_lv8_0) else "0";
    icmp_ln51_fu_552_p2 <= "1" when (unsigned(idx_fu_126) > unsigned(ap_const_lv16_3B)) else "0";
    idx_1_load_fu_342_p1 <= idx_fu_126;
    idx_2_fu_348_p2 <= std_logic_vector(unsigned(idx_fu_126) + unsigned(ap_const_lv16_1));
    keep_1_out <= keep_fu_178;

    keep_1_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, beat_last_reg_857, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (beat_last_reg_857 = ap_const_lv1_1))) then 
            keep_1_out_ap_vld <= ap_const_logic_1;
        else 
            keep_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    meta_chanspec_out <= empty_fu_166;

    meta_chanspec_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, beat_last_reg_857, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (beat_last_reg_857 = ap_const_lv1_1))) then 
            meta_chanspec_out_ap_vld <= ap_const_logic_1;
        else 
            meta_chanspec_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    meta_core_spatial_out <= p_0_0_0589767_fu_150;

    meta_core_spatial_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, beat_last_reg_857, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (beat_last_reg_857 = ap_const_lv1_1))) then 
            meta_core_spatial_out_ap_vld <= ap_const_logic_1;
        else 
            meta_core_spatial_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    meta_rssi_out <= p_0_0_0589778_fu_154;

    meta_rssi_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, beat_last_reg_857, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (beat_last_reg_857 = ap_const_lv1_1))) then 
            meta_rssi_out_ap_vld <= ap_const_logic_1;
        else 
            meta_rssi_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    meta_seq_out <= empty_20_fu_170;

    meta_seq_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, beat_last_reg_857, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (beat_last_reg_857 = ap_const_lv1_1))) then 
            meta_seq_out_ap_vld <= ap_const_logic_1;
        else 
            meta_seq_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    n_sub_3_fu_644_p2 <= std_logic_vector(unsigned(n_sub_fu_142) + unsigned(ap_const_lv16_1));
    n_sub_3_out <= n_sub_fu_142;

    n_sub_3_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, beat_last_reg_857, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (beat_last_reg_857 = ap_const_lv1_1))) then 
            n_sub_3_out_ap_vld <= ap_const_logic_1;
        else 
            n_sub_3_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    phase_load_load_fu_586_p1 <= phase_fu_174;

    rx_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, rx_TVALID, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            rx_TDATA_blk_n <= rx_TVALID;
        else 
            rx_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    rx_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            rx_TREADY <= ap_const_logic_1;
        else 
            rx_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    tmp_1_fu_427_p4 <= (rx_TDATA & empty_20_fu_170(7 downto 0));
    tmp_2_fu_407_p4 <= (empty_fu_166(15 downto 8) & rx_TDATA);
    tmp_3_fu_392_p4 <= (rx_TDATA & empty_fu_166(7 downto 0));
    tmp_4_fu_558_p4 <= n_sub_fu_142(15 downto 8);
    tmp_fu_442_p4 <= (empty_20_fu_170(15 downto 8) & rx_TDATA);
end behav;
